# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Countries' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Countries
 pod 'Alamofire', '~> 5.5.0'
 pod 'SDWebImage', '~> 5.12.3'
 pod 'SDWebImageSVGCoder', '~> 1.6.1'
 pod 'SnapKit', '~> 5.0.1'
  target 'CountriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountriesUITests' do
    # Pods for testing
  end

end
